mendersoftware/deviceauth

- README.md
Signed-off-by: Maciej Mrowiec <mrowiec.maciej@gmail.com>
> Add code coverage badge and go report card badge

- .travis.yml
Signed-off-by: Maciej Mrowiec <mrowiec.maciej@gmail.com>
> Switch coverage counting in atomic mode. Removed godep references.

- devauth.go
- devauth_test.go
Issues: MEN-639
@bboozzoo @maciejmrowiec pls review
> devauth: add a check if device exists before propagating device acceptation

- api_devauth.go
Issues: MEN-501
@maciejmrowiec  @mchalski
> api_devadm: unified api error output (details logged)

- api_devauth.go
- api_devauth_test.go
- docs/devices_api.yml
- docs/internal_api.yml
* added "request_id" field to error response body
Issues: MEN-501
@mchalski @maciejmrowiec
> Unify API error output

- README.md
- config/config.go
- config/config_test.go
- main.go
- main_test.go
Issues: MEN-702
@kjaskiewiczz  @maciejmrowiec
> Exposing service configuration through environment

- client_deviceadm.go
- client_deviceadm_test.go
Api change from https://github.com/mendersoftware/deviceadm/pull/45
@GregorioDiStefano @maciejmrowiec 
Signed-off-by: Marek Świecznik <marek.swiecznik@rndity.com>
> client_deviceadm: change put /devices returning status to match API change

- .travis.yml
- docs/internal_api.yml
- tests/Dockerfile
- tests/build-acceptance
- tests/common.py
- tests/conftest.py
- tests/docker-compose.yml
- tests/run-acceptance
- tests/run.sh
- tests/tests/client.py
- tests/tests/test_device.py
- tests/tests/test_token.py
@mendersoftware/rndity @GregorioDiStefano @maciejmrowiec
> acceptance tests

- accesslog/middleware.go
- api_devauth.go
- api_devauth_mock_test.go
- api_devauth_test.go
- client_deviceadm.go
- client_deviceadm_test.go
- client_inventory.go
- client_inventory_test.go
- datastore.go
- datastore_mongo.go
- datastore_mongo_test.go
- devauth.go
- devauth_test.go
- init_dbtest_test.go
- jwt_agent.go
- jwt_agent_test.go
- key.go
- key_test.go
- main.go
- middleware_test.go
- routing.go
- routing_test.go
- server.go
- server_test.go
- version_test.go
Addresses problems raised in https://tracker.mender.io/browse/MEN-827
> no key load on request

- tests/docker-compose.yml
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>
> use correct container when testing

- Dockerfile
- config.go
- config.yaml
> do not ship token signing key in container

- .travis.yml
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>
> bump from go 1.7 to 1.7.4

- api_devauth.go
- api_devauth_test.go
- utils/http.go
- utils/http_test.go
Issues: MEN-881
using conventions from:
https://tools.ietf.org/html/rfc3986#section-5.4
> relative url in Location header

- LIC_FILES_CHKSUM.sha256
- datastore.go
- datastore_mock_test.go
- datastore_mongo.go
- datastore_mongo_test.go
- main.go
- vendor/github.com/mendersoftware/go-lib-micro/LICENSE
- vendor/github.com/mendersoftware/go-lib-micro/mongo/migrate/db.go
- vendor/github.com/mendersoftware/go-lib-micro/mongo/migrate/init_dbtest_test.go
- vendor/github.com/mendersoftware/go-lib-micro/mongo/migrate/migration.go
- vendor/github.com/mendersoftware/go-lib-micro/mongo/migrate/migrator.go
- vendor/github.com/mendersoftware/go-lib-micro/mongo/migrate/migrator_dummy.go
- vendor/github.com/mendersoftware/go-lib-micro/mongo/migrate/migrator_dummy_test.go
- vendor/github.com/mendersoftware/go-lib-micro/mongo/migrate/version.go
- vendor/github.com/mendersoftware/go-lib-micro/mongo/migrate/version_test.go
- vendor/vendor.json
> Mongo schema version

- tests/docker-compose.yml
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>
> use correct container when running acceptance tests

- .travis.yml
* Remove autosetting latest docker tag for master
* Remove github releases
* Remove upload of binaries to S3
Signed-off-by: Maciej Mrowiec <mrowiec.maciej@gmail.com>
> Cleanup travis setup

- .travis.yml
Signed-off-by: Maciej Mrowiec <mrowiec.maciej@gmail.com>
> Deploy documentation on every build

- docs/management_api.yml
> api: docs: device decommission endpoint spec

- api_devauth.go
- api_devauth_test.go
- datastore.go
- datastore_mock_test.go
- datastore_mongo.go
- datastore_mongo_test.go
- devauth.go
- devauth_mock_test.go
- devauth_test.go
- model_device.go
NOTE: No decommissioning job submitting.
> Decommissioning device

- .travis.yml
- Dockerfile.acceptance-testing
- main_test.go
- tests/docker-compose.yml
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>
> calculate acceptance test coverage

- docs/management_api.yml
> API docs wording fixes

- main.go
- store/mongo/datastore_mongo.go
- tests/run.sh
> fsync & journal

- tests/docker-compose.yml
- tests/run.sh
- tests/tests/client.py
- tests/tests/test_device.py
> acceptance tests: decommission device

- config.go
> config: introduce TenantAdmAddr setting

- .travis.yml
- client/orchestrator/client_orchestrator.go
- client/tenant/client_tenantadm.go
- devauth/devauth.go
- devauth/devauth_test.go
- server.go
- tests/Dockerfile
- tests/common.py
- tests/docker-compose-tenant.yml
- tests/docker-compose.yml
- tests/run.sh
- tests/tests/client.py
- tests/tests/deviceadm.py
- tests/tests/inventory.py
- tests/tests/mockserver.py
- tests/tests/tenantadm.py
- tests/tests/test_device.py
- tests/tests/test_tenant.py
- tests/tests/test_token.py
@mendersoftware/rndity @maciejmrowiec @GregorioDiStefano 
also must be tested with https://github.com/mendersoftware/integration/pull/242
> multi tenant acceptance tests

- client/orchestrator/client_orchestrator.go
- server.go
- tests/docker-compose.yml
- tests/run.sh
- tests/tests/client.py
- tests/tests/mockserver.py
- tests/tests/test_device.py
https://github.com/mendersoftware/deviceauth/pull/137 plus few extra commits that potentially missed
> 1.1.x withtenanttests

- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
- store/mongo/migration_1_1_0.go
https://tracker.mender.io/browse/MEN-1383
> ensure db indexes on all write operations

- devauth/devauth.go
https://tracker.mender.io/browse/MEN-1327
> reject request with tenant token in single tenant setup

- devauth/devauth.go
https://tracker.mender.io/browse/MEN-1327
> devauth/token verification: reject tokens with tenant claim in single tenant setup

- .travis.yml
- Dockerfile.acceptance-testing
- devauth/devauth.go
- devauth/devauth_test.go
- jwt/claims.go
- tests/tests/test_token.py
@mendersoftware/rndity @maciejmrowiec @GregorioDiStefano
> MEN-1418 `mender.device` claim

- client/orchestrator/client_orchestrator.go
- devauth/devauth.go
@mendersoftware/rndity @maciejmrowiec @GregorioDiStefano 
Have not updated the tests yet.
Goes with: https://github.com/mendersoftware/integration/pull/354
> MEN-1441: decommissioning multitenant

- devauth/devauth_test.go
- tests/tests/test_device.py
Some updates to tests around decommissioning. Trying to make them more specific and with more cases.
> decommissioning improve tests

- devauth/devauth.go
- devauth/devauth_test.go
- main_test.go
- store/datastore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
- tests/docker-compose-tenant.yml
- tests/docker-compose.yml
@mendersoftware/rndity @maciejmrowiec 
Mostly complete, still need to update acceptance tests though.
> MEN-1417 reject other auth sets when accepting one

- docs/management_api.yml
> MEN-1420 docs: add spec for GET /limits/max_devices

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- devauth/devauth.go
- devauth/devauth_test.go
- devauth/mocks/App.go
- docs/internal_api.yml
- model/limit.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
> MEN-1421 limits and internal PUT endpoint

- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
- vendor/github.com/mendersoftware/go-lib-micro/mongo/migrate/migrator_dummy.go
- vendor/github.com/mendersoftware/go-lib-micro/mongo/migrate/migrator_dummy_test.go
- vendor/github.com/mendersoftware/go-lib-micro/store/utils.go
- vendor/github.com/mendersoftware/go-lib-micro/store/utils_test.go
- vendor/vendor.json
@mendersoftware/rndity comments & review please
> migration fix

- docs/management_api.yml
https://tracker.mender.io/browse/MEN-1483
> docs/management: GET /devices/count?status

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- devauth/devauth.go
- devauth/devauth_test.go
- devauth/mocks/App.go
https://tracker.mender.io/browse/MEN-1422
this is a stale pr - I closed the task without ever making one (!).
> get max device count - internal endpoint

- .travis.yml
- main.go
- store/mongo/datastore_mongo.go
- tests/Dockerfile
- tests/common.py
- tests/tests/client.py
- tests/tests/test_cli.py
https://tracker.mender.io/browse/MEN-1244
@maciejmrowiec @mendersoftware/rndity 
acceptance tests finally fixed, see last commit
note that coverage is down - I didn't want to unit test the command, lots of effort, acceptance tests are provided instead.
> deviceauth migrate --tenant

- tests/common.py
- tests/tests/client.py
- tests/tests/test_cli.py
- tests/tests/test_device.py
- tests/tests/test_limits.py
- tests/tests/test_tenant.py
- tests/tests/test_token.py
> use fixtures in acceptance tests

- tests/tests/inventory.py
- tests/tests/test_device.py
> tests: add test for limiting of accepted devices 

- docs/management_api.yml
- tests/common.py
- tests/tests/client.py
- tests/tests/test_device.py
- tests/tests/test_limits.py
- tests/tests/test_tenant.py
> tests: add test for the simplest case of device counts, fix max device limit tests

- tests/common.py
- tests/tests/test_device.py
> extend device counting acceptance tests

- client/deviceadm/client_deviceadm.go
- tests/tests/deviceadm.py
needed by https://github.com/mendersoftware/deviceadm/pull/110
related to https://github.com/mendersoftware/mender-api-gateway-docker/pull/79
> client/deviceadm: update to new deviceadm routing conventions

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- devauth/devauth.go
- devauth/devauth_test.go
- devauth/mocks/App.go
- docs/internal_api.yml
- main.go
- model/tenant.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
- tests/tests/client.py
- tests/tests/test_internal_api.py
> POST /tenants

- docs/management_api.yml
Issues: https://tracker.mender.io/browse/MEN-1633
> docs: management endpoint for removing device authentication sets

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- devauth/devauth.go
- devauth/devauth_test.go
- devauth/mocks/App.go
- docs/management_api.yml
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
Issue: https://tracker.mender.io/browse/MEN-1634
> management endpoint for removing device auth sets 

- docs/management_api.yml
- store/mongo/datastore_mongo.go
- tests/common.py
- tests/tests/client.py
- tests/tests/test_device.py
- tests/tests/test_preauth.py
Issues: https://tracker.mender.io/browse/MEN-1632
@maciejmrowiec @mendersoftware/rndity 
depends on: https://github.com/mendersoftware/deviceauth/pull/181
> POST /devices acceptance tests

- api/http/api_devauth.go
- client/deviceadm/client_deviceadm.go
- client/deviceadm/client_deviceadm_test.go
- client/deviceadm/mocks/ClientRunner.go
- client/deviceadm/status.go
- devauth/devauth.go
- devauth/devauth_test.go
- model/authset.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
Issues: https://tracker.mender.io/browse/MEN-1636
> update auth request handling (preauthorization)

- .travis.yml
> travis: drop deprecated --email flag from 'docker login'

- devauth/devauth.go
- devauth/devauth_test.go
@mendersoftware/rndity @maciejmrowiec @GregorioDiStefano
> devauht: fix GetAuthSetById method error handling

- api/http/api_devauth.go
- api/http/api_devauth_test.go
@mendersoftware/rndity @maciejmrowiec @GregorioDiStefano
> api/http: fix DeleteAuthSet method error handling 

- devauth/devauth.go
- tests/common.py
- tests/tests/client.py
- tests/tests/test_submit_auth_req.py
- tests/tests/test_tenant.py
https://tracker.mender.io/browse/MEN-1637
> new Auth Request handling - acceptance test

- cmd/commands.go
- tests/docker-compose.yml
- tests/tests/client.py
- tests/tests/test_cli.py
Issue: https://tracker.mender.io/browse/MEN-1650
@maciejmrowiec @GregorioDiStefano @mchalski
>  acceptance tests for 'deviceauth migrate --list-tenants' cli method

- docs/internal_api.yml
Issue: https://tracker.mender.io/browse/MEN-1695
Epic: https://tracker.mender.io/browse/MEN-1685
@mchalski @maciejmrowiec @GregorioDiStefano
> docs/API: internal endpoint for removing device tokens

- .travis.yml
- store/mongo/datastore_mongo_test.go
Signed-off-by: Gregorio Di Stefano <greg.distefano+github@gmail.com>
> travis: bump to golang 1.10

- cmd/commands.go
- cmd/commands_test.go
- cmd/main_test.go
- main.go
- model/token.go
- store/mongo/datastore_mongo_cleanup.go
- store/mongo/datastore_mongo_cleanup_test.go
Issue: https://tracker.mender.io/browse/MEN-1745
@mchalski @maciejmrowiec @GregorioDiStefano
> Maintenance CLI for cleaning up failed decommissioning operations

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- cmd/commands.go
- cmd/commands_test.go
- cmd/main_test.go
- devauth/devauth.go
- devauth/devauth_test.go
- devauth/mocks/App.go
- main.go
- model/token.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_cleanup.go
- store/mongo/datastore_mongo_cleanup_test.go
- store/mongo/datastore_mongo_test.go
- store/mongo/migration_1_0_0_test.go
- store/mongo/migration_1_1_0.go
- vendor/github.com/mendersoftware/mendertesting/check_license_go_code.sh
- vendor/vendor.json
Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
> Update mendertesting dependency and affected copyright years.

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- client/deviceadm/client_deviceadm_test.go
- client/orchestrator/client_orchestrator_test.go
- client/tenant/client_tenantadm.go
- client/tenant/client_tenantadm_test.go
- client/testing/client.go
- devauth/devauth.go
- devauth/devauth_test.go
- tests/tests/test_tenant.py
https://tracker.mender.io/browse/MEN-1711
> extend token issuing process with "account suspended" error handling

- cmd/commands_test.go
- devauth/devauth.go
- model/authset.go
- model/device.go
- store/mongo/datastore_mongo_cleanup_test.go
- store/mongo/datastore_mongo_test.go
- store/mongo/migration_1_1_0.go
https://tracker.mender.io/browse/MEN-1679
> don't save tenant token

- devauth/devauth.go
- devauth/devauth_test.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_cleanup.go
- store/mongo/datastore_mongo_test.go
Issues: https://tracker.mender.io/browse/MEN-1895
> Trigger device acceptance workflow in conductor only if device previously not in accepted state

- .travis.yml
- api/http/api_devauth.go
- api/http/api_devauth_test.go
- devauth/devauth.go
- devauth/devauth_test.go
- devauth/mocks/App.go
- docs/internal_api.yml
- model/status.go
https://tracker.mender.io/browse/MEN-1899
> get device's status (internal api)

- tests/tests/test_tokens_delete.py
Issues: https://tracker.mender.io/browse/MEN-1697
> tests/acceptance: tests for internal endpoint for removing tokens

- tests/Dockerfile
- tests/tests/test_tenant.py
Issues: https://tracker.mender.io/browse/MEN-1712
> tests/acceptance: test token issuing for suspended tenant account

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- docs/management_api_admission.yml
- server.go
https://tracker.mender.io/browse/MEN-1923
> migrate PUT /admission/devices/:id/status

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- docs/management_api_admission.yml
Issues: https://tracker.mender.io/browse/MEN-1924
> migrate deviceadm's GET /api/management/v1/admission/devices/:aid/status enpoint

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- docs/management_api_admission.yml
- model/authset.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
https://tracker.mender.io/browse/MEN-1926
> GET /admission/devices

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- docs/management_api_admission.yml
- model/devadm-authset-req.go
Issues: https://tracker.mender.io/browse/MEN-1925
> POST /api/management/v1/admission/devices endpoint 

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- docs/management_api_admission.yml
https://tracker.mender.io/browse/MEN-1927
> GET /api/management/v1/admission/devices/:id

- .travis.yml
- tests/Dockerfile
- tests/common.py
- tests/conftest.py
- tests/run.sh
- tests/tenantadm.py
- tests/tests/client.py
- tests/tests/test_admission.py
Issues: https://tracker.mender.io/browse/MEN-1937
> admission API acceptance tests

- .travis.yml
- api/http/api_devauth_test.go
- devauth/devauth_test.go
- model/authreq.go
- model/preauthreq.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
- store/mongo/migration_1_2_0.go
- store/mongo/migration_1_2_0_test.go
- tests/common.py
- tests/tests/deviceadm.py
- tests/tests/test_device.py
- tests/tests/test_preauth.py
- tests/tests/test_submit_auth_req.py
- utils/json_util.go
- utils/json_util_test.go
https://tracker.mender.io/browse/MEN-1901
we now sort id data by keys, and store the sorted string representation. this makes the (pre)auth api immune to id data reordering, extra spaces, etc.
escaping is still required, but as a bonus we actually verify that the data is valid json. all these improvements leave almost no room for user error, since the only error-prone quirk we have left - escaping - will be verified during this validation.
> improve id data parsing / api usability

- devauth/devauth.go
- devauth/devauth_test.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
- store/mongo/migration_1_4_0.go
- store/mongo/migration_1_4_0_test.go
Issues: https://tracker.mender.io/browse/MEN-2081
> proper handling of the device status

- store/mongo/migration_1_2_0.go
- store/mongo/migration_1_2_0_test.go
- store/mongo/migration_1_3_0.go
- store/mongo/migration_1_3_0_test.go
- store/mongo/migration_1_4_0_test.go
Issues: https://tracker.mender.io/browse/MEN-2196
> store/mongo: fix database migrations

- api/http/api_devauth.go
- docs/management_api_v2.yml
Issues: https://tracker.mender.io/browse/MEN-1984
> version 2 of the management API

- api/http/api_devauth.go
- devauth/devauth.go
- devauth/devauth_test.go
addition to https://tracker.mender.io/browse/MEN-1985
> identity data handling - save identity data object and hash

- store/mongo/datastore_mongo.go
> changelog: actually run migration 1.5.0

- devauth/devauth_test.go
- store/mongo/datastore_mongo_test.go
> devauth: fix db ver in tests

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- api/http/model_pre_auth_req.go
- devauth/devauth.go
- devauth/devauth_test.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
- store/mongo/migration_1_0_0_test.go
- tests/Dockerfile
- tests/README.md
Issues: https://tracker.mender.io/browse/MEN-2220
> POST /devices API v2 endpoint - endpoint for preauthorizing devices

- devauth/devauth.go
- devauth/devauth_test.go
Issues: https://tracker.mender.io/browse/MEN-2234
> devauth: update the device status when processing new authentication reqest from the device

- .travis.yml
- devauth/devauth.go
- devauth/devauth_test.go
Issue: https://tracker.mender.io/browse/MEN-2234
> devauth: update device status when processing new authentication request from the device

- .travis.yml
- docs/management_api.yml
Issues: https://tracker.mender.io/browse/MEN-1987
> changelog: docs: API v1 deprecation note

- devauth/devauth.go
- devauth/devauth_test.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
this is a fix for an apparent driver or db issue - see tickets for description.
Issues: MEN-2272, 2267
passing build is here:
https://mender-jenkins.mender.io/job/mender-builder/label=googlecloud%20&&%20mender_servers/2120/consoleFull
there's just the create organization error, which is expected
> devauth: when updating auth set, update by id

- api/http/api_devauth.go
- api/http/api_devauth_test.go
Devauth management API v1 and admission API removed.
Issues: https://tracker.mender.io/browse/MEN-2307
> api/http: remove management API v1 and admission API endpoints

- client/inventory/client.go
- client/inventory/client_test.go
- main.go
found when actually testing:
https://tracker.mender.io/browse/MEN-2482
needed for: https://github.com/mendersoftware/integration/pull/622
> cli: propagate-inventory fixes

- .gitlab-ci.yml
- .travis.yml
- cmd/commands_test.go
> mongo settings for failing maintenance test

- docs/management_api.yml
> removed superfluous response type definition in swagger docs

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- docs/management_api.yml
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>
> Return device id to a POST /devauth/devices call

- devauth/devauth_test.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
- store/mongo/migration_1_6_0.go
New index containing sha256 of identity data and public key created.
Devauth App is looking for auth set existence querying by sha256 of
identity data and public key.
> mongodb: create index on auth sets collection

- .gitlab-ci.yml
- Dockerfile.acceptance-testing
- tests/docker-compose-acceptance-enterprise.yml
- tests/docker-compose-acceptance.yml
- tests/tests/test_cli.py
- tests/tests/test_device.py
- tests/tests/test_tenant.py
- tests/tests/test_tokens_delete.py
> QA-149: Use pipelines templates - 2.2.x

- client/inventory/client.go
- client/inventory/client_test.go
- client/inventory/mocks/Client.go
- cmd/commands.go
- cmd/commands_test.go
- cmd/main_test.go
- main.go
ChangeLog:title
(cherry picked from commit db5536e88b902db27a51de654a09551211776a1c)
> propagate-inventory-statuses command added

- docs/internal_api.yml
- docs/management_api.yml
> Clarify description of the 'per_page` parameter in API calls

- cmd/commands.go
The migrate command, when used without the `--tenant` option, migrates
the database of all the tenants. This behaviour is consistent with the
`--automigrate` option of the `server` command.
If the `--tenant` option is specified, the migration runs only for the
provided tenant ID.
> Update migrate command to be consistent with server --automigrate

- devauth/devauth.go
- vendor/github.com/mendersoftware/go-lib-micro/plan/plans.go
- vendor/github.com/mendersoftware/go-lib-micro/plan/plans_test.go
- vendor/github.com/mendersoftware/go-lib-micro/plan/pricing.go
- vendor/vendor.json
> Set plan to enterprise if running in single-tenant mode

- api/http/api_devauth.go
- api/http/api_devauth_test.go
> api/http: allow verification requests also on GET requests

- client/inventory/client.go
- client/inventory/client_test.go
- client/inventory/mocks/Client.go
- cmd/commands.go
- devauth/devauth.go
- main.go
- server.go
> MEN-3637 update device identity via internal inventory endpoint.

- cache/cache.go
- cache/cache_test.go
- cache/mocks/Cache.go
- devauth/devauth.go
- devauth/devauth_test.go
https://tracker.mender.io/browse/MEN-3631
https://tracker.mender.io/browse/MEN-3632
> cache: clear device JWTs on device rejection scenarios

- docs/devices_api.yml
- docs/management_api.yml
> API spec fixes: schema and hostname - 2.3.x

- client/inventory/client.go
- client/orchestrator/client_orchestrator.go
- client/tenant/client_tenantadm.go
Follow-up bugfixes from integration testing.
> client: Fix typo in health check handlers

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- docs/internal_api.yml
> MEN-3923: add internal end-point to retrieve the count of devices

- tests/Dockerfile
- tests/docker-compose-acceptance-enterprise.yml
- tests/docker-compose-acceptance.yml
replaced current in-project image with tiny variant to ensure template compatibility
> tests: switched image used in acceptance tests to prebuilt one

- config.yaml
> Fix typo in config.yaml

- devauth/devauth.go
- devauth/devauth_test.go
> MEN-4114: improve deletion of preauthorized devices from inventory

- devauth/devauth.go
> Do not update the device if the status did not change

- client/orchestrator/models.go
- devauth/devauth.go
- devauth/devauth_test.go
> MEN-4208: add tenant_id input parameter to the decommissioning workflow

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- devauth/devauth.go
Signed-off-by: Marcin Chalczynski <m.chalczynski@gmail.com>
> all: use traefik forwarding headers

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- devauth/devauth.go
https://tracker.mender.io/browse/MEN-4327
> merge feature-traefik

- access/addons.go
- access/checker.go
- access/checker_test.go
- api/http/api_devauth.go
- config.yaml
- config/config.go
- devauth/devauth.go
- go.mod
- go.sum
- server.go
- tests/docker-compose-acceptance-enterprise.yml
- tests/tests/test_token.py
- tests/tests/test_tokens_delete.py
- vendor/github.com/mendersoftware/go-lib-micro/context/httpheader/header.go
- vendor/modules.txt
Since there are no plan restrictions for devices (yet) I didn't implement that part, but I tried to keep the `access` package flexible with this in mind.
> MEN-4512: Addon restrictions for devices

- model/device.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
- store/mongo/migration_1_10_0.go
- store/mongo/migration_1_10_0_test.go
- tests/tests/test_cli.py
> MEN-4601: add index to list/count devices by status

- client/inventory/client.go
has to go together with https://github.com/mendersoftware/inventory/pull/275
> inventory client: update the path of the status endpoint

- api/http/api_devauth.go
- devauth/devauth.go
- devauth/devauth_test.go
https://tracker.mender.io/browse/MEN-4919
> MEN-4919: auth set status change validation

- client/orchestrator/client_orchestrator_test.go
- client/orchestrator/models.go
- cmd/commands.go
> MEN-5124: do not hard-code the email sender, rely on workflows' default

- .gitlab-ci.yml
- api/http/api_devauth.go
- api/http/routing.go
- cache/cache.go
- client/inventory/client.go
- client/orchestrator/client_orchestrator.go
- client/tenant/client_tenantadm.go
- client/testing/client.go
- cmd/commands.go
- devauth/devauth.go
- main.go
- middleware.go
- model/authset.go
- model/device.go
- store/datastore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_cleanup.go
- store/mongo/migration_1_2_0.go
- store/mongo/migration_1_3_0.go
- store/mongo/migration_1_5_0.go
- store/mongo/migration_1_6_0.go
- store/mongo/migration_1_7_0.go
- store/mongo/migration_1_8_0.go
- store/mongo/migration_1_9_0.go
- utils/http.go
- utils/testing/util.go
> QA-235: pipeline: Switch to static checks by golangci-lint

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- client/orchestrator/client_orchestrator.go
- client/orchestrator/models.go
- devauth/devauth.go
- devauth/devauth_test.go
- devauth/mocks/App.go
- docs/internal_api.yml
- model/device.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
Relates to mendersoftware/azure-iot-manager#16
> [MEN-5245] Provision device identity and update status on rejection

- config/config.go
> Unused settings cleanup: SettingDevAdmAddr

- docs/management_api.yml
Add device_id to the AuthSet object in management OpenAPI spec
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>
> QA-118 develop mender SDK

- Dockerfile
- Dockerfile.acceptance-testing
- LICENSE
- LIC_FILES_CHKSUM.sha256
Cherry pick of PR: #556
For you :)
> [Cherry 3.1.x]: Changelog:All: Bump alpine from 3.14.2 to 3.15.0 #568

- api/http/api_devauth_test.go
- cmd/commands_test.go
- devauth/devauth_test.go
- model/device.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_cleanup_test.go
- store/mongo/datastore_mongo_test.go
- store/mongo/migration_1_11_0.go
- store/mongo/migration_1_11_0_test.go
- store/mongo/migration_1_2_0_test.go
- store/mongo/migration_1_3_0.go
- store/mongo/migration_1_3_0_test.go
- store/mongo/migration_1_4_0_test.go
- store/mongo/migration_1_5_0_test.go
- store/mongo/migration_1_9_0_test.go
> refactor: do not store the public key in the device document

- Dockerfile
- Dockerfile.acceptance-testing
> chore: moved docker image away from root

- api/http/api_devauth.go
- client/inventory/client.go
- client/inventory/client_test.go
- client/tenant/client_tenantadm.go
- client/tenant/client_tenantadm_test.go
> fix: replace colon with hash for path params modifiers in URLs

- client/inventory/client.go
> fix: Missing hash in inventory client

- api/http/api_devauth.go
- devauth/devauth.go
- devauth/devauth_test.go
- devauth/mocks/App.go
- docs/internal_api.yml
- tests/docker-compose-acceptance.yml
- tests/tests/client.py
- tests/tests/test_device.py
- tests/tests/test_mgnt_v2.py
Ticket: ME-41
Signed-off-by: Alex Miliukov <oleksandr.miliukov@northern.tech>
> ME-41: device decommissioning data inconsistency

- LICENSE
- LIC_FILES_CHKSUM.sha256
- devauth/devauth.go
Ticket: [MEN-6211](https://tracker.mender.io/browse/MEN-6211)
> fix: trigger reporting reindex on device decommissioning

- client/orchestrator/client_orchestrator.go
- client/orchestrator/client_orchestrator_test.go
- client/orchestrator/mocks/ClientRunner.go
- cmd/commands.go
- cmd/commands_test.go
- main.go
> feat: CLI command to reindex to the reporting service all the devices

- tests/tests/orchestrator.py
- tests/tests/test_cli.py
> fix(ci): mock `reindex_reporting`

- devauth/devauth.go
- devauth/devauth_test.go
I think that we should update last check-in on auth successful auth. opinions?
Ticket: None
> chore: update last check-in on successful auth

- devauth/devauth.go
> chore: logging fixes: jti.String() with %s

- LICENSE
- LIC_FILES_CHKSUM.sha256
- devauth/devauth.go
- devauth/devauth_test.go
- tests/docker-compose-acceptance-enterprise.yml
- tests/docker-compose-acceptance.yml
Ticket: MEN-6504
Signed-off-by: Krzysztof Jaskiewicz <krzysztof.jaskiewicz@northern.tech>
(cherry picked from commit ee36e559adba14c7bb83e5646008522eb2fc8cbf)
> fix: do not accept device which is being decommissioned

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- devauth/devauth.go
- devauth/devauth_test.go
- tests/tests/test_internal_api.py
The handler initializes unused collections in MongoDB.
> chore: Cleanup redundant multi-tenant endpoint

- cmd/commands.go
> fix: propagate id data to inventory for all tenants case.

- .gitlab-ci.yml
- Dockerfile
Ticket: QA-613
Changelog: Added multiplaform build
> Multiplaform build

- api/http/api_devauth.go
Ticket: MEN-5497
Changelog: feat: optimize the authentication requests checking the `X-MEN-Signature` value only for successful authentication requests
> feat: optimize authentication requests and the signature verification

- cache/cache.go
Ticket: MEN-6926
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>
(cherry picked from commit 03c012b8999f828c9a1e8c005ac8aa789af79d29)
> fix: Redis key prefix configuration not applied

- api/http/model_pre_auth_req.go
- devauth/devauth.go
- devauth/devauth_test.go
- docs/management_api.yml
- model/preauthreq.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
test: https://github.com/mendersoftware/integration/pull/2576
Ticket: MEN-6961
> feat: accept and support preauth at any time

- devauth/devauth.go
- devauth/devauth_test.go
> feat: sync check_in_time with inventory if reporting is disabled
