mendersoftware/deviceauth

- api_devauth.go
- api_devauth_mock_test.go
- api_devauth_test.go
- client_deviceadm.go
- devauth.go
- devauth_test.go
- docs/internal_api.yml
- model_admreq.go
* enable setting `pending` status in API for a device (and update docs)
* update `deviceadm` client to conform https://github.com/mendersoftware/deviceadm/pull/45 changes
* add ResetDevice method for setting `pending` status
Issues: MEN-650
@mchalski @maciejmrowiec
> Cleanup API for submitting device for admission

- .travis.yml
- tests/README.md
- tests/build-acceptance
- tests/common.py
- tests/docker-compose.yml
- tests/run-acceptance
- tests/run.sh
- tests/tests/test_token.py
@mendersoftware/rndity @GregorioDiStefano 
I've tried to generalize `run-acceptance` so that it could become a part of integration repository rather than that of a specific service. This led to minor changes in `build-acceptance`. The script is supposed to build the image for acceptance tests container. So any image/service specific pieces (like copy of extra files) were moved there.
On top of this, there's a readme detailing running and building processes.
> acceptance tests seqnum

- .travis.yml
- tests/docker-compose-integration.yml
This is done inside the tests themselves now.
Signed-off-by: Kristian Amlie <kristian.amlie@mender.io>
> Remove use of docker-compose before integration tests.

- api_devauth.go
- devauth.go
- devauth_test.go
Distinguish cases where there's a different device ID, but the same device
key (device identity data has changed) and same device ID but different
key (device key changed).
The first case may happen when the end user is using device attributes that are
not immutable (ex. ethernet MAC address of Raspberry Pi is changed on each
boot).
The second case corresponds to key rotation, which is not yet handled.
> devauth: api: log ID and key mismatch

- LIC_FILES_CHKSUM.sha256
- docs/devices_api.yml
- middleware.go
- vendor/github.com/mendersoftware/go-lib-micro/customheader/middleware.go
- vendor/github.com/mendersoftware/go-lib-micro/customheader/middleware_test.go
- vendor/vendor.json
Change public routing to v1, v2, v3 schema (v1).
Update documentation.
Remove port 8080 from swagger.
Add service version header returned by API
@mendersoftware/rndity
> MEN-963 Versioning

- api_devauth.go
Removing endpoints that have no implementation and are not covered by the spec.
Fixes: [MEN #969]
> api_devauth: remove endpoints with no implementation

- api_devauth.go
- api_devauth_test.go
- docs/internal_api.yml
- tests/tests/test_device.py
- tests/tests/test_token.py
Do not return 303 See Other on PUT to /api/0.1.0/devices/:id/status as this
would redirect to an endpoint that no longer exists.
> api: internal: no See Other on device status PUT

- devauth.go
Only devices which are successfully added to device admission should be stored in local database.
TODO: update acceptance tests
> Add device to local database only if it was successfully added to admission service

- devauth/devauth.go
- devauth/devauth_test.go
- jwt/jwt_agent.go
- model/device.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
Details are covered in commit 
https://github.com/mendersoftware/deviceauth/commit/41d4aec24a25521719661a0b1a20e4de09d694aa
Note that there is still a chance that device will be created in inventory if attributes PATCH request goes through token verification before decommissioning commenced but the actual requested is proxied to inventory after DELETE device was run. Fixing this would require a change in how PATCH on device attributes works.
@mendersoftware/rndity @maciejmrowiec @GregorioDiStefano 
Best if verifed with https://github.com/mendersoftware/mender-api-gateway-docker/pull/64 otherwise correlating all logs with their corresponding requests may not be accurate.
> decommissioning fix

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- devauth/devauth.go
- devauth/devauth_test.go
- devauth/mocks/App.go
- docs/internal_api.yml
- model/limit.go
issues: https://tracker.mender.io/browse/MEN-1423
the first 3 commits actually unify the name of the `max_devices` param across the codebase.
> get max devices limit (mgmt endpoint)

- tests/tests/client.py
- tests/tests/test_limits.py
- /tenant/{tenant_id}/limits/max_devices endpoint tests (GET and PUT methods)
- swagger spec validation enabled
> tests/acceptance: test /tenant/{tenant_id}/limits/max_devices endpoint

- .travis.yml
- api/http/api_devauth.go
- api/http/api_devauth_test.go
- devauth/devauth.go
- devauth/devauth_test.go
- devauth/mocks/App.go
- model/count.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
https://tracker.mender.io/browse/MEN-1484
involves a pretty horrific mongo aggregation pipeline (to count devices by status), so take a good look.
can filter by status in general, not only 'accepted' devices. this required more work but thought it would be useful to handle this once and for all and not go back to it. other statuses might still be relevant e.g. for the ui in the future.
also, had to bump mongo version on travis to 3.4. we're still stuck at 3.2 (which imo should be fixed across the board). I got bitten by an incompatibility - the `$count` aggregate operator is available since 3.4, hence the fix.
> GET /devices/count?status

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- devauth/devauth.go
- devauth/devauth_test.go
- docs/management_api.yml
- tests/tests/client.py
- tests/tests/test_device.py
https://tracker.mender.io/browse/MEN-1486
this is part 1 of the work. next PR will go into `deviceadm` (propagate the new 422 status to the user when accepting a device, with the exact same message).
> enforce device count limit

- devauth/devauth.go
set the 'accepted' status just before returning to the main routine -
but not before, the struct is being used to match a 'preauthorized' entry
in the db ('accepted' will never match).
> devauth: fix preauth case handling in POST /auth_requests 

- api/http/api_devauth_test.go
- tests/common.py
- tests/docker-compose-tenant.yml
- tests/tests/client.py
- tests/tests/test_device.py
- tests/tests/test_preauth.py
- tests/tests/test_tenant.py
https://tracker.mender.io/browse/MEN-1635
Contains:
- the original PPs pull request (2 commits)
- a multitude of critical fixes for acceptance tests (MT-related)
@mendersoftware/rndity @maciejmrowiec 
replaces: https://github.com/mendersoftware/deviceauth/pull/188
> acc tests for delete authset + various fixes

- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
https://tracker.mender.io/browse/MEN-1752
> fix: Deleting AuthSets and Tokens uses single item delete call  

- .travis.yml
This reverts commit 304fbe7daa4bd1ed610a193e52d6c3c0afa01bb7.
> Revert "travis: update from Go 1.8 to 1.10"

- devauth/devauth.go
- devauth/devauth_test.go
- tests/tests/test_device.py
don't remove the device because that might leave dangling data
in other services with no possibility of decommissioning/removal.
only delete the device if the authset was preauthorized - that's a guarantee
data was not propagated yet anywhere else.
> devauth: fix auth set removal

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
With this PR it should be possible to use devices/count endpoint to count devices with status 'preauthorized':
GET devauth/devices/count?status=preauthorized
Issues: https://tracker.mender.io/browse/MEN-1884
> count devices with 'preauthorized' status

- docs/management_api_admission.yml
so far this lives in the 'deviceadm' branch, but we need
to test new rendering somehow. a build will push docs to s3.
> test: upload the extra admission doc to test s3

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- devauth/devauth_test.go
- model/devadm-authset-req.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
- store/mongo/migration_1_3_0.go
- store/mongo/migration_1_3_0_test.go
- tests/tests/test_admission.py
by mistake key normalization was introduced to the `deviceadm` service while the devauth-devadm merge was already in progress (in https://github.com/mendersoftware/deviceadm/pull/136).
port these changes to the admission portion of the `devauth` api.
we completely forgot about id data normalization in admission preauth though, so introduce that too (until now only the internal devauth EP had that, and that's useless especially after the services are merged).
Issues: https://tracker.mender.io/browse/MEN-1900, https://tracker.mender.io/browse/MEN-1901
> id data and public key normalization in admission preauth api  

- docs/management_api_v2.yml
When there is a conflict while preauthorizing devices, return
conflicting device in 409 Conflict response body.
> docs: management API v2: POST devices/: return conflicting device

- store/mongo/migration_1_4_0.go
- store/mongo/migration_1_4_0_test.go
Migration 1.4.0 is setting device statuses based on devices
authentication set statuses.
If the device has no authentication sets then set device status to
"rejected" (there is no better status in this case).
Signed-off-by: Krzysztof Jaskiewicz <krzysiekjaskiewicz@gmail.com>
> store/mongo: fix migration 1.4.0

- .travis.yml
Travis is cloning repositories with depth=50 by default.
We need full git history for validating copyright year of each file.
> travis conf: disable git shallow clone

- .travis.yml
- client/tenant/client_tenantadm.go
- client/tenant/client_tenantadm_test.go
- config.yaml
- config/config.go
- devauth/devauth.go
- devauth/devauth_test.go
- server.go
It can be used to allow devices that don't have a tenant token to be
allowed into a specific tenant's list of devices. Enable it either
using the `DEVICEAUTH_DEFAULT_TENANT_TOKEN` environment variable, or
the `default_tenant_token` setting in `config.yaml`.
MEN-2705
MEN-2706
Changelog: Commit
Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
> Add support for default tenant token.

- devauth/devauth.go
- devauth/devauth_test.go
MigrateTenant always migrates the default db.
the main cause is - we're not setting up the context correctly with the
tenant's id.
actually, it works in part on the default db, in part on the tenant's db
(we use straight dbname in places, and context in others).
causes extremely difficult bugs when e.g. migrating from os to
enterprise (tenant's db needs migrating, so we try - but data
is taken from the default db, so it fails on dup keys).
Signed-off-by: Marcin Chalczynski <m.chalczynski@gmail.com>
> devauth: fix context handling in ProvisionTenant

- .gitlab-ci.yml
It seems like a new package has been released upstream so the previous
one is not available anymore.
> Update openssl lib version used in unit tests

- devauth/devauth_test.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
- store/mongo/migration_1_6_0.go
New index containing sha256 of identity data and public key created.
Devauth App is looking for auth set existance querying by sha256 of
identity data and public key.
> mongodb: create index on auth sets collection

- tests/docker-compose-integration.yml
- tests/docker-compose-tenant.yml
- tests/docker-compose.yml
Update docker-compose version to 2.1 for acceptance tests to comply with the rest of the integration compose files.
Also, remove docker-compose-integration.yml
> Update docker-compose version to 2.1 for acceptance tests

- .gitlab-ci.yml
- LICENSE
- LIC_FILES_CHKSUM.sha256
Update golang version for unit tests to 1.11; same version as we use for the actual build.
> Update golang version for unit tests to 1.11

- .gitlab-ci.yml
- Dockerfile.acceptance-testing
- tests/docker-compose-acceptance-enterprise.yml
- tests/docker-compose-acceptance.yml
- tests/tests/test_cli.py
- tests/tests/test_device.py
- tests/tests/test_tenant.py
- tests/tests/test_tokens_delete.py
Use of CI templates and related fixes.
Depends on https://github.com/mendersoftware/mendertesting/pull/43, commit [31545bd](https://github.com/mendersoftware/deviceauth/pull/310/commits/31545bd2170e08e4c1285fd3641b21bade79338f) will be removed before merge.
> QA-149: Use pipelines templates

- client/tenant/client_tenantadm.go
- client/tenant/client_tenantadm_test.go
- client/tenant/mocks/ClientRunner.go
- client/tenant/tenant.go
- devauth/devauth.go
- devauth/devauth_test.go
- jwt/claims.go
- tests/common.py
https://tracker.mender.io/browse/MEN-3312
add a Plan field to the token issued to the device, so that device APIs will be able to inspect it and switch on it. 
the immediate use is differentiating provides/depends support in `deployments`.
the bare minimum is done in unit/acceptance to get green builds, but the JWT plan verification is done in backend-integration: https://github.com/mendersoftware/integration/pull/864
combined pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/pipelines/132122327
comment: https://tracker.mender.io/browse/MEN-3312?focusedCommentId=105920&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-105920
> device gets tenant's plan in JWT

- .gitignore
- api/http/api_devauth.go
- client/orchestrator/client_orchestrator.go
- client/orchestrator/mocks/ClientRunner.go
- cmd/commands_test.go
- devauth/devauth.go
- devauth/devauth_test.go
- model/authset.go
- tests/common.py
- tests/tests/orchestrator.py
- tests/tests/test_device.py
- tests/tests/test_mgnt_v2.py
- tests/tests/test_tenant.py
- tests/tests/test_token.py
- tests/tests/test_tokens_delete.py
Propagate device status to inventory
--
* **deviceauth** calls _update_device_status_ [[1](https://github.com/mendersoftware/workflows/pull/40)] workflow to propagate information on device status to inventory.
* **inventory** exposes internal API to set status for a list of devices [[2](https://github.com/mendersoftware/inventory-enterprise/pull/24)].
* _/filters/search_ can be use by UI to get list of devices as a single place of information.
related PRs:
* [1] https://github.com/mendersoftware/workflows/pull/40
* [2] https://github.com/mendersoftware/inventory/pull/162
* [3] https://github.com/mendersoftware/deviceauth/pull/324
ChangeLog:none
> MEN-3240 propagate device status to inventory: use the wf

- config/config.go
- devauth/devauth.go
- devauth/devauth_test.go
- server.go
The configuration option is considered redundant and is overridden in
enterprise environments.
> Remove DEVICEAUTH_MAX_DEVICES_LIMIT_DEFAULT configuration option

- model/api_limits.go
- model/device.go
- store/mongo/datastore_mongo_test.go
https://tracker.mender.io/browse/MEN-3551
tenant-wide ratelimits can be overriden, per device.
overrides will be soon inspected/compared in token verification, i.e. around here: https://github.com/mendersoftware/deviceauth/blob/master/devauth/devauth.go#L996
I'm reusing the same generic structures as https://github.com/mendersoftware/tenantadm/pull/153 - I'll move them to go-lib-micro as a next step.
> ratelimit overrides for tenant-wide settings

- cache/cache.go
- cache/cache_test.go
- utils/time.go
Quick followup based on demo feedback:
https://tracker.mender.io/browse/MEN-3698
A new burst tracking strategy is implemented, where a device spamming more frequently than `min_interval_sec` will be still allowed every `min_interval_sec`. This is contrary to the old strategy, where the device would be denied every time just because of the short burst time.
It's implemented similarily to quotas (multiple burst keys, one per min_interval_sec time window, rolling over regularly and expiring accordingly).
Aside from that, some general improvements in cache tests are introduced (mock time source for cache, emulate time flow for both miniredis and cache to capture limit counters actually being created and rolled over in both components).
> throttling: don't lock out device forever when it doesn't respect bursts

- docs/devices_api.yml
- docs/management_api.yml
* [API spec] Consistently use host hosted.mender.io across all repos
* [API spec] Consistently use https schemes across all repos
> API spec fixes: schema and hostname

- model/device.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_cleanup_test.go
- store/mongo/datastore_mongo_test.go
- store/mongo/migration_1_1_0.go
- store/mongo/migration_1_9_0.go
- store/mongo/migration_1_9_0_test.go
- tests/tests/test_cli.py
prevents 'index key too large' errors.
https://tracker.mender.io/browse/MEN-3816
> index on id data sha256, not id data

- store/mongo/migration_1_9_0.go
- store/mongo/migration_1_9_0_test.go
workaround for staging mostly.
Signed-off-by: Marcin Chalczynski <m.chalczynski@gmail.com>
> store: migration 1.9.0 doesn't fail on no index

- tests/Dockerfile
- tests/common.py
- tests/tests/client.py
- tests/tests/cryptutil.py
- tests/tests/test_cli.py
- tests/tests/test_internal_api.py
- tests/tests/test_mgnt_v2.py
Python 3.5 has already reached EOL so bumped the image to python 3.8.
Moreover, pycrypto seems to no longer be maintained and makes use of
deprecated function time.clock breaking compatibility with python 3.8
leading to the replacement with `cryptography` package. Finally, the
pymongo version was bumped to the latest stable as well to suppress some
deprecation warnings.
> tests: Update docker image and python packages for acceptance tests

- client/orchestrator/client_orchestrator.go
- client/orchestrator/models.go
- devauth/devauth.go
- devauth/devauth_test.go
- go.mod
- go.sum
- tests/tests/orchestrator.py
- vendor/github.com/urfave/cli/app.go
- vendor/github.com/urfave/cli/command.go
- vendor/github.com/urfave/cli/context.go
- vendor/github.com/urfave/cli/flag_int64_slice.go
- vendor/github.com/urfave/cli/flag_int_slice.go
- vendor/github.com/urfave/cli/flag_string_slice.go
- vendor/modules.txt
This PR updates the parameters passed to `provision_device` workflow to include `tenant_id` and `device_id` instead of `model.Device`.
> MEN-4062: Add deviceconnect service to workflows

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- devauth/devauth.go
In case an authset is not found when verifying a JWT token, we returned
500 internal server error. We change the behaviour to return 401
Unauthorized, letting the device to ask for a new JWT token.
> Fix: return 401 unauthorized on ErrAuthSetNotFound

- api/http/api_devauth.go
- api/http/api_devauth_test.go
- cmd/commands.go
- cmd/commands_test.go
- docs/management_api.yml
- model/device.go
- model/device_test.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
New endpoint `POST /api/management/v2/devauth/devices/search`
>    The endpoint acts as a POST form version of
>    GET /api/management/v2/devauth/devices
>    with the exact same parameters. This commit also allows querying over
>    both multiple and singular device statuses and ids to both endpoints.
>    The new POST endpoint accepts both 'application/json' and
>    'application/x-www-form-urlencoded' (the latter will not be enabled by
>    default middleware, however).
> MEN-3763: New endpoint for querying devices with auth sets

- devauth/devauth.go
- devauth/devauth_test.go
- model/device.go
If the backend is under load (many new devices authorizing), it can
happen the status attribute is not propagated to the inventory service.
This leads to a device not visible in the UI, but correctly provisioned
as pending in deviceauth.
To avoid it we update the flow of the auth request:
1. Default status for devices is noauth
2. Auth request processing happens as usual
3. The workflow execution to update the status in inventory is started
4. If no error happened in 1-3, we updated the status in db to pending
In case of failure, the status in the db will be noauth, which will
trigger a new sync to inventory because noauth != pending.
Changelog: fix status propagation to inventory for pending devices
(cherry picked from …
> MEN-4604: make sure the status is propagated to inventory for pending devices

- tests/docker-compose-acceptance.yml
Randomly discovered this when doing QA-159.
> tests: Mount volume collecting acceptance tests coverage for open-source

- docs/devices_api.yml
> MEN-4670: api docs, /auth_requests does not require the JWT token

- client/orchestrator/models.go
- devauth/devauth.go
- devauth/devauth_test.go
- tests/tests/orchestrator.py
The device provisioning and decommissioning workflows don't require the
authorization header anymore.
> MEN-4525: device provisioning and decommissioning workflow updates

- Dockerfile
- Dockerfile.acceptance-testing
Bumps alpine from 3.14.2 to 3.15.0.
---
updated-dependencies:
- dependency-name: alpine
dependency-type: direct:production
update-type: version-update:semver-minor
...
Signed-off-by: dependabot[bot] <support@github.com>
(cherry picked from commit e89cba34a42277836ce051094c8121c519ad5275)
> Changelog:All: Bump alpine from 3.14.2 to 3.15.0

- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
By first sorting by status, the query is always backed by the index `tenant_id_status__id`.
> perf(mongo): Sort devices by status then ID for GET /devices

- devauth/devauth.go
- devauth/devauth_test.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
The previous behavior was putting the device in a conflicting state and
returning 500 errors on auth requests. With this PR, the
preauthorized auth set will take precedence and take over as the
accepted auth set.
> ALV-213: Handle preauthorized auth sets when device is accepted

- devauth/devauth.go
- store/datastore.go
- store/mocks/DataStore.go
- store/mongo/datastore_mongo.go
- store/mongo/datastore_mongo_test.go
Updates the behavior of the Preauthorize endpoint if "force" paremeter is set:
* If an authset already exist, the status will be forced to "preauthorized".
* If the auth set does not exist, a new one will be created.
Changelog: Commit
Ticket: MEN-7241
> fix: Preauthorize force behavior applies to existing auth sets

- cache/cache.go
- cache/cache_test.go
The lookup for `check_in_time` from the cache does not work when running
Redis in cluster mode because of the MGET command requires keys to hash
to the same slot. This commit replaces MGET with multiple batched GET
commands when running Redis in cluster mode.
Changelog: Commit
Ticket: MEN-7337
> fix: Inconsistent device check_in_time when listing devices
